export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const UPDATE = "UPDATE";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_CART_DETAIL = "GET_CART_DETAIL";
export const GET_PRODUCT = "GET_PRODUCT";
export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const ADD_ITEM_ERROR = "ADD_ITEM_ERROR";
export const ORDER = "ORDER";

export const MARK_AS_COMPLETED = "MARK_AS_COMPLETED";
export const MARK_AS_CANCELED = "MARK_AS_CANCELED";
export const INIT_ORDERS = "INIT_ORDERS";

export const INIT_PRODUCTS = "INIT_PRODUCTS";
export const REMOVE_PRODUCT = "REMOVE_PRODUCTS";

export const OPEN_SIGNIN_MODAL = "OPEN_SIGNIN_MODAL";
export const OPEN_SIGNUP_MODAL = "OPEN_SIGNUP_MODAL";
export const CLOSE_SIGNIN_MODAL = "CLOSE_SIGNIN_MODAL";
export const CLOSE_SIGNUP_MODAL = "CLOSE_SIGNUP_MODAL";
export const CLOSE_ALL_MODAL = "CLOSE_ALL_MODAL";
